### PR TITLE
fix(result): correctly shortening results to 2500 chars, added unit test

### LINKED ISSUE #159: [BUG] Description clipping not working
image
Description too long

### PR DESCRIPTION
**Pull request by aleksasiriski**
Closes https://github.com/hearchco/frontend/issues/159

The bug was that the code was modifying a copy of slice element instead of the actual element. Also, decided to move the functionality to search func instead of only when returning the results via router and to modify the passed slice instead of making a copy.

Had to switch from:
```go
for _, result := range results {
  ...
}
```

To:
```go
for i := range results {
  result := &results[i]
  ...
}
```

### CODE REVIEW

**Review by k4lizen — APPROVED** [review]

File: src/search/result/shorten.go [hunk 1]
```diff
@@ -1,21 +1,29 @@
 package result
 
-func firstNchars(str string, n int) string {
+func FirstNchars(str string, n int) string {
 	v := []rune(str)
-	if n >= len(v) {
+	if n < 0 || n >= len(v) {
 		return str
 	}
 	return string(v[:n])
```
Comment (aleksasiriski) [inline src/search/result/shorten.go:8]: I think this will panic if n==0, so the above if should use `n<=0` not `n<0`
