### PR TITLE
fix: improve sanitization of result fields by refactoring some functionality

### LINKED ISSUE #192: [BUG] Search result title html not being parsed
**Describe the bug**
Search result title html is not being parsed. 

**Screenshots**
image

### PR DESCRIPTION
**Pull request by k4lizen**
Probably Closes #192 

+ allow nil results to enter AddSEResult
+ let MakeSEResult check validity of result instead of it being checked in every engine
+ add sanitizaiton functions to _sedefaults
+ added two functions which extract url, title, and description fields from a html DOM, using dompaths
    + add error messages for invalid results
+ refactored all engines to use these functions
+ made brave and yahoo selectors more specific, so they don't match invalid result fields

### CODE REVIEW

File: src/search/engines/yahoo/yahoo.go [hunk 1]
```diff
@@ -46,19 +45,43 @@ func Search(ctx context.Context, query string, relay *bucket.Relay, options engi
...
+			return
 		}
+
+		if !labelExists {
+			log.Error().
+				Str("engine", Info.Name.String()).
+				Str("url", linkText).
+				Str("title", titleText).
+				Str("description", descText).
+				Msgf("yahoo.Search(): aria attribute doesn't exist on matched title element (%v)", dompaths.Title)
```
Comment (aleksasiriski) [inline src/search/engines/yahoo/yahoo.go]: why %v instead of field?

File: src/search/engines/etools/etools.go [hunk 2]
```diff
@@ -35,30 +34,20 @@ func Search(ctx context.Context, query string, relay *bucket.Relay, options engi
 	var pageRankCounter []int = make([]int, options.MaxPages*Info.ResultsPerPage)
 
 	col.OnHTML(dompaths.Result, func(e *colly.HTMLElement) {
-		dom := e.DOM
+		linkText, titleText, descText := _sedefaults.RawFieldsFromDOM(e.DOM, &dompaths, Info.Name) // telemetry url isnt valid link so cant pass it to FieldsFromDOM (?)
```
Comment (aleksasiriski) [inline src/search/engines/etools/etools.go:37]: why &dompaths instead of dompaths

File: src/search/bucket/addresult.go [hunk 3]
```diff
@@ -9,6 +9,10 @@ import (
 )
 
 func AddSEResult(seResult *result.RetrievedResult, seName engines.Name, relay *Relay, options *engines.Options, pagesCol *colly.Collector) {
+	if seResult == nil {
```
Comment (aleksasiriski) [inline src/search/bucket/addresult.go:12]: when does this happen?

File: src/search/engines/_sedefaults/fields.go [hunk 4]
```diff
@@ -0,0 +1,61 @@
...
+	"strings"
+
+	"github.com/PuerkitoBio/goquery"
+	"github.com/hearchco/hearchco/src/search/engines"
+	"github.com/hearchco/hearchco/src/search/parse"
+	"github.com/rs/zerolog/log"
+)
+
+// Fetches from DOM via dompaths. Returns (url, title, description)
+func RawFieldsFromDOM(dom *goquery.Selection, dompaths *engines.DOMPaths, seName engines.Name) (string, string, string) {
```
Comment (aleksasiriski) [inline src/search/engines/_sedefaults/fields.go]: does pointer for goquery.Selection and engines.DOMPaths bring any noticable performance benefits? if not, better to copy since it assures no changes when returned

File: src/search/bucket/makeresult.go [hunk 5]
```diff
@@ -3,9 +3,21 @@ package bucket
 import (
 	"github.com/hearchco/hearchco/src/search/engines"
 	"github.com/hearchco/hearchco/src/search/result"
+	"github.com/rs/zerolog/log"
 )
 
+// Returns nil on invalid data
 func MakeSEResult(urll string, title string, description string, searchEngineName engines.Name, sePage int, seOnPageRank int) *result.RetrievedResult {
```
Comment (aleksasiriski) [inline src/search/bucket/makeresult.go:10]: returned pointers are always heap allocated and there are a lot of RetrievedResults (Garbage Collector may go insane when we start having actual users)

File: src/search/engines/_sedefaults/fields.go (hunk 4 above)
Comment (k4lizen) [reply src/search/engines/_sedefaults/fields.go]: The dom (goquery.Selection) is given as a pointer by colly. The dompaths could be passed by value, but since this function is called on every result (for most engines), its probably best to keep it pointer (it would be consistent with the codebase currently, per-result structs are passed by pointer). I will add a comment to the function though.

File: src/search/bucket/addresult.go [hunk 6]
```diff
@@ -8,8 +8,27 @@ import (
...
+	}
+
+	// TODO: add a check if image result is valid
+	if seResult.URL == "" || seResult.Title == "" {
+		log.Error().
+			Str("engine", seName.String()).
+			Str("url", seResult.URL).
+			Str("title", seResult.Title).
+			Str("description", seResult.Description).
+			Msg("bucket.AddSEResult(): invalid result, some fields are empty.")
```
Comment (aleksasiriski) [inline src/search/bucket/addresult.go]: remove . from Msg

File: src/search/bucket/addresult.go [hunk 7]
```diff
@@ -8,8 +8,27 @@ import (
...
 
-// passing pointers down is on stack
-func AddSEResult(seResult *result.RetrievedResult, seName engines.Name, relay *Relay, options engines.Options, pagesCol *colly.Collector) {
+// Checks if the retrieved result is valid. Makes a result object and adds it to the relay.
+// Returns true if the result is valid (false otherwise).
+func AddSEResult(seResult *result.RetrievedResult, seName engines.Name, relay *Relay, options *engines.Options, pagesCol *colly.Collector) bool {
+	if seResult == nil {
+		log.Error().
+			Str("engine", seName.String()).
+			Msg("bucket.AddSEResult(): nil result.")
```
Comment (aleksasiriski) [inline src/search/bucket/addresult.go]: remove . from Msg

File: src/search/engines/_sedefaults/fields.go (hunk 4 above)
Comment (aleksasiriski) [reply src/search/engines/_sedefaults/fields.go]: Dompaths is just a few strings, you're already making more strings using `dom.Find`. All of that gets cleaned up quickly since it's on stack. Don't see a point making it a pointer, only allows for bugs to crawl up in the future.

For goquery it's ok if it already was a pointer.

File: src/search/engines/_sedefaults/fields.go [hunk 8]
```diff
@@ -0,0 +1,63 @@
...
+
+func SanitizeTitle(titleText string) string {
+	return parse.ParseTextWithHTML(strings.TrimSpace(titleText))
+}
+
+func SanitizeDescription(descText string) string {
+	return parse.ParseTextWithHTML(strings.TrimSpace(descText))
+}
+
+func SanitizeFields(linkText string, titleText string, descText string) (string, string, string) {
```
Comment (aleksasiriski) [inline src/search/engines/_sedefaults/fields.go:59]: If you send dompaths as pointer, why wouldn't these be pointers then? Same logic, it's just a group of few strings.

File: src/search/bucket/addresult.go [hunk 9]
```diff
@@ -8,8 +8,27 @@ import (
 	"github.com/rs/zerolog/log"
 )
 
-// passing pointers down is on stack
-func AddSEResult(seResult *result.RetrievedResult, seName engines.Name, relay *Relay, options engines.Options, pagesCol *colly.Collector) {
+// Checks if the retrieved result is valid. Makes a result object and adds it to the relay.
+// Returns true if the result is valid (false otherwise).
+func AddSEResult(seResult *result.RetrievedResult, seName engines.Name, relay *Relay, options *engines.Options, pagesCol *colly.Collector) bool {
```
Comment (aleksasiriski) [inline src/search/bucket/addresult.go]: options should stay pass-by-copy to ensure adding a result doesn't change it for other results, it's also a small struct consisting of 4 bools, 2 int and 3 strings.

File: src/search/engines/brave/options.go [hunk 10]
```diff
@@ -11,8 +11,8 @@ var Info = engines.Info{
 	ResultsPerPage: 20,
 }
 
-var dompaths = engines.DOMPaths{
-	Result:      "div.snippet",
+var dompaths engines.DOMPaths = engines.DOMPaths{
```
Comment (aleksasiriski) [inline src/search/engines/brave/options.go]: engines.DOMPaths before = accidentally added

File: src/search/engines/duckduckgo/duckduckgo.go [hunk 11]
```diff
@@ -50,17 +50,25 @@ func Search(ctx context.Context, query string, relay *bucket.Relay, options engi
...
+						Str("engine", Info.Name.String()).
+						Str("url", linkText).
+						Str("title", titleText).
+						Str("description", descText).
+						Msgf("duckduckgo.Search(): href attribute doesn't exist on matched URL element (%v)", dompaths.Link)
+					return
 				}
+
+				res := bucket.MakeSEResult(linkText, titleText, descText, Info.Name, page, (i/4 + 1))
+				bucket.AddSEResult(&res, Info.Name, relay, &options, pagesCol)
```
Comment (aleksasiriski) [inline src/search/engines/duckduckgo/duckduckgo.go]: Missing returned bool check (valid := and if valid)

File: src/search/engines/startpage/startpage.go [hunk 12]
```diff
@@ -26,28 +25,15 @@ func Search(ctx context.Context, query string, relay *bucket.Relay, options engi
...
-			res := bucket.MakeSEResult(linkText, titleText, descText, Info.Name, page, pageRankCounter[pageIndex]+1)
-			bucket.AddSEResult(&res, Info.Name, relay, options, pagesCol)
+		pageIndex := _sedefaults.PageFromContext(e.Request.Ctx, Info.Name)
+		page := pageIndex + options.Pages.Start + 1
 
+		res := bucket.MakeSEResult(linkText, titleText, descText, Info.Name, page, pageRankCounter[pageIndex]+1)
+		valid := bucket.AddSEResult(&res, Info.Name, relay, &options, pagesCol)
+		if valid {
 			pageRankCounter[pageIndex]++
-		} else {
```
Comment (aleksasiriski) [inline src/search/engines/startpage/startpage.go:44]: Removed else logging on purpose?

File: src/search/engines/yahoo/options.go [hunk 13]
```diff
@@ -15,8 +15,8 @@ var Info = engines.Info{
 	ResultsPerPage: 10,
 }
 
-var dompaths = engines.DOMPaths{
-	Result:      "div#main > div > div#web > ol > li",
+var dompaths engines.DOMPaths = engines.DOMPaths{
```
Comment (aleksasiriski) [inline src/search/engines/yahoo/options.go]: accidentally added engines.DOMPaths before =

File: src/search/engines/yahoo/yahoo.go (hunk 1 above)
Comment (aleksasiriski) [reply src/search/engines/yahoo/yahoo.go]: why %v instead of field?

**Review by aleksasiriski — CHANGES_REQUESTED** [review]
I will need to take a look again to see if I missed something, but overall looks very good and is a much needed addition to the code base.

File: src/search/engines/duckduckgo/duckduckgo.go (hunk 11 above)
Comment (k4lizen) [reply src/search/engines/duckduckgo/duckduckgo.go]: What should happen if its invalid?

File: src/search/engines/startpage/startpage.go (hunk 12 above)
Comment (k4lizen) [reply src/search/engines/startpage/startpage.go:44]: Well yeah it happens inside `bucket.AddSEResult` and `_sedefaults.FieldsFromDOM` now.

File: src/search/engines/duckduckgo/duckduckgo.go (hunk 11 above)
Comment (aleksasiriski) [reply src/search/engines/duckduckgo/duckduckgo.go]: Oh right there's no need for `pageRankCounter[pageIndex]++`. My bad.

File: src/search/engines/duckduckgo/duckduckgo.go [hunk 14]
```diff
@@ -50,17 +50,25 @@ func Search(ctx context.Context, query string, relay *bucket.Relay, options engi
...
-				if hrefExists && linkText != "" && linkText != "#" && titleText != "" {
-					res := bucket.MakeSEResult(linkText, titleText, descText, Info.Name, page, (i/4 + 1))
-					bucket.AddSEResult(&res, Info.Name, relay, options, pagesCol)
+				if !hrefExists {
+					log.Error().
+						Str("engine", Info.Name.String()).
+						Str("url", linkText).
+						Str("title", titleText).
+						Str("description", descText).
+						Msgf("duckduckgo.Search(): href attribute doesn't exist on matched URL element (%v)", dompaths.Link)
```
Comment (aleksasiriski) [inline src/search/engines/duckduckgo/duckduckgo.go]: Why %v instead of field? You can do CTRL+F with `Msgf` as input and make sure that there are none

**Review by aleksasiriski — DISMISSED** [review]
Missed one field last time, but it's all good (you can force merge after that simple fix).
